version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6380
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6380"]
