apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlz-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlz-app
  template:
    metadata:
      labels:
        app: hlz-app
    spec:
      containers:
      - name: hlz-app
        image: marcolap13/userapi_redis:latest
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "mon-redis"
          - name: REDIS_PORT
            value: "6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
