apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  AZURE_CACHE_FOR_REDIS_HOST_NAME: TEhaLVByb2plY3QucmVkaXMuY2FjaGUud2luZG93cy5uZXQ=
  AZURE_CACHE_FOR_REDIS_ACCESS_KEY: R3JxdTQ5S1ZWYWx6N2ZiVTdXbUtUNjBUeFpTQTFKTXJuQXpDYVAydFE5ST0=
