apiVersion: v1
kind: Service
metadata:
  name: hlz-app-service
spec:
  selector:
    app: hlz-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort