apiVersion: v1
kind: Service
metadata:
  name: hlz-app-service
spec:
  type: NodePort
  ports:
    - port: 12345
      targetPort: 3000
      nodePort: 30001
  selector:
    app: hlz-app

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
