apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlz-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlz-app
  template:
    metadata:
      labels:
        app: hlz-app
    spec:
      containers:
        - name: hlz-app
          image: bensaebe/hlz_app
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6380"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6380
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
