version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    ports:
      - "6379:6379"